package com.incedo.personalhealth.core.designsystem

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

@Immutable
data class PhColors(
    val primary: Color,
    val primaryHover: Color,
    val primaryPressed: Color,
    val primarySoft: Color,
    val onPrimary: Color,
    val accent: Color,
    val accentSoft: Color,
    val background: Color,
    val backgroundSoft: Color,
    val surface: Color,
    val surfaceRaised: Color,
    val surfaceMuted: Color,
    val surfaceSunken: Color,
    val divider: Color,
    val border: Color,
    val borderStrong: Color,
    val text: Color,
    val textMuted: Color,
    val textFaint: Color,
    val onPrimaryText: Color,
    val success: Color,
    val successSoft: Color,
    val warning: Color,
    val warningSoft: Color,
    val danger: Color,
    val dangerSoft: Color,
    val info: Color,
    val infoSoft: Color,
    val data: List<Color>,
    val zones: List<Color>,
    val isDark: Boolean
)

val PhLightColors = PhColors(
    primary = Color(0xFF2F6F4E),
    primaryHover = Color(0xFF275E42),
    primaryPressed = Color(0xFF1F4F37),
    primarySoft = Color(0xFFE2EEE7),
    onPrimary = Color(0xFFFFFFFF),
    accent = Color(0xFF7AB89A),
    accentSoft = Color(0xFFDBEDE2),
    background = Color(0xFFF4F7F5),
    backgroundSoft = Color(0xFFECF1ED),
    surface = Color(0xFFFFFFFF),
    surfaceRaised = Color(0xFFFFFFFF),
    surfaceMuted = Color(0xFFEEF2EF),
    surfaceSunken = Color(0xFFE4EAE6),
    divider = Color(0xFFDDE4DF),
    border = Color(0xFFCFD8D2),
    borderStrong = Color(0xFF1F2A24),
    text = Color(0xFF1F2A24),
    textMuted = Color(0xFF5A6B62),
    textFaint = Color(0xFF8A9991),
    onPrimaryText = Color(0xFFFFFFFF),
    success = Color(0xFF2F6F4E),
    successSoft = Color(0xFFE2EEE7),
    warning = Color(0xFFC7873A),
    warningSoft = Color(0xFFF6EBD9),
    danger = Color(0xFFB14A4A),
    dangerSoft = Color(0xFFF4DEDE),
    info = Color(0xFF3A6F8A),
    infoSoft = Color(0xFFE0EBF1),
    data = listOf(
        Color(0xFF2F6F4E),
        Color(0xFF7AB89A),
        Color(0xFFC7873A),
        Color(0xFF3A6F8A),
        Color(0xFF8E6FA8),
        Color(0xFFB14A4A),
        Color(0xFF4F6B5C)
    ),
    zones = listOf(
        Color(0xFFB5CFC0),
        Color(0xFF7AB89A),
        Color(0xFF4E9C77),
        Color(0xFFC7873A),
        Color(0xFFB14A4A)
    ),
    isDark = false
)

val PhDarkColors = PhColors(
    primary = Color(0xFF7AB89A),
    primaryHover = Color(0xFF8DC4A8),
    primaryPressed = Color(0xFF69A88A),
    primarySoft = Color(0xFF1A3329),
    onPrimary = Color(0xFF0E1F17),
    accent = Color(0xFFA6D6BA),
    accentSoft = Color(0xFF1F3B2D),
    background = Color(0xFF0E1714),
    backgroundSoft = Color(0xFF131E1A),
    surface = Color(0xFF16221E),
    surfaceRaised = Color(0xFF1B2A24),
    surfaceMuted = Color(0xFF1F302A),
    surfaceSunken = Color(0xFF0B1411),
    divider = Color(0xFF233129),
    border = Color(0xFF2C3D34),
    borderStrong = Color(0xFFE6EDE8),
    text = Color(0xFFE6EDE8),
    textMuted = Color(0xFF9AAAA0),
    textFaint = Color(0xFF6E7E74),
    onPrimaryText = Color(0xFF0E1F17),
    success = Color(0xFF7AB89A),
    successSoft = Color(0xFF1F3B2D),
    warning = Color(0xFFE1A75A),
    warningSoft = Color(0xFF3A2C12),
    danger = Color(0xFFE27A7A),
    dangerSoft = Color(0xFF3A1E1E),
    info = Color(0xFF7DA9C0),
    infoSoft = Color(0xFF1B2C36),
    data = listOf(
        Color(0xFF7AB89A),
        Color(0xFFA6D6BA),
        Color(0xFFE1A75A),
        Color(0xFF7DA9C0),
        Color(0xFFB8A0D0),
        Color(0xFFE27A7A),
        Color(0xFF99B0A4)
    ),
    zones = listOf(
        Color(0xFF2C3D34),
        Color(0xFF4F8467),
        Color(0xFF7AB89A),
        Color(0xFFE1A75A),
        Color(0xFFE27A7A)
    ),
    isDark = true
)
